export enum Constants {
    DATABASE_CONNECTION = 'DATABASE_CONNECTION',
    DATABASE_COLLECTION_ACTIVITY_FEED = 'KysoActivityFeed',
    DATABASE_COLLECTION_FILE = 'File',
    DATABASE_COLLECTION_KYSO_SETTINGS = 'KysoSettings',
}
